import { Task, Sprint, UserProfile, MasterData, AppRole } from '../../types';

export interface IssueListViewProps {
  projectRole?: string;
  tasks: Task[];
  roots: Task[];
  sprints: Sprint[];
  projectMembers: UserProfile[];
  allUsers: UserProfile[];
  masterData: MasterData[];
  userRole: AppRole;
  user: UserProfile | null;
  currentUserProfile: UserProfile;
  hasPermission: any;
  updateTaskField: (id: string, field: string, value: any) => void;
  deleteTask?: (id: string) => void;
  bulkDeleteTasks?: (taskIds: string[]) => void;
  handleQuickCreate: (title: string, type: string) => void;
  setSelectedTaskForDetail: (t: Task | null) => void;
  setIsTaskDetailModalOpen: (open: boolean) => void;
  setIsNewTaskModalOpen?: (open: boolean) => void;
  selectedProject: any;
  fetchTasks?: () => void;
}

export interface TaskDetailModalProps {
  projectRole?: string;
  isUpdatingTask?: Record<string, boolean>;
  isOpen: boolean;
  onClose: () => void;
  task: Task | null;
  tasks: Task[];
  projectMembers: UserProfile[];
  masterData: MasterData[];
  userRole: AppRole;
  user: UserProfile | null;
  currentUserProfile: UserProfile;
  sprints: Sprint[];
  updateTaskField: (id: string, field: string, value: any) => void;
  hasPermission: any;
  activityLogs: any[];
  comments: any[];
  newCommentText: string;
  setNewCommentText: (t: string) => void;
  handleAddComment: () => void;
  handleFileUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleRemoveAttachment?: (attachmentId: string) => void;
  uploadProgress: Record<string, number>;
  isLoggedIn: boolean;
  handleQuickAddSubtask: (parentId: string, type: string) => void;
  mentionState: any;
  handleSelectMention: (username: string) => void;
  handleCommentChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
  removeTaskLink: (taskId: string, linkId: string) => void;
  handleAddLinkedTask: () => void;
  handleRemoveLinkedTask: (taskId: string, linkId: string) => void;
  taskLinkTargetId: string;
  setTaskLinkTargetId: (id: string) => void;
  taskLinkRelation: any;
  setTaskLinkRelation: (rel: any) => void;
  isAddingTaskLink: boolean;
  setIsAddingTaskLink: (add: boolean) => void;
  isAddingExternalLink: boolean;
  setIsAddingExternalLink: (add: boolean) => void;
  newExternalLinkTitle: string;
  setNewExternalLinkTitle: (t: string) => void;
  newExternalLinkUrl: string;
  setNewExternalLinkUrl: (t: string) => void;
  handleAddExternalLink: () => void;
  removeExternalLink: (taskId: string, linkId: string) => void;
  toggleBlockedStatus: (taskId: string) => void;
  handleSuggestStoryPoints: (task: Task) => void;
  handleAddLink: () => void;
  newLinkTitle: string;
  setNewLinkTitle: (t: string) => void;
  newLinkUrl: string;
  setNewLinkUrl: (t: string) => void;
  isAddingLink: boolean;
  setIsAddingLink: (add: boolean) => void;
  deleteTask: (id: string) => void;
}
