import React from 'react';
import {
  Layout, 
  Plus, 
  TrendingUp,
  Search, 
  Settings, 
  LogOut, 
  User, 
  Kanban, 
  ListTodo, 
  Users, 
  ChevronRight,
  ChevronLeft,
  MoreVertical,
  Trash2,
  Edit2,
  Calendar,
  X,
  CheckCircle2,
  Clock,
  AlertCircle,
  AlertTriangle,
  LayoutDashboard,
  Eye,
  Layers,
  ExternalLink,
  Database,
  Zap,
  ChevronDown,
  Share2,
  Filter,
  UserCircle,
  CircleDot,
  Target,
  Copy,
  Mail,
  Check,
  ArrowRight,
  ArrowUpDown,
  History,
  MessageSquare,
  Paperclip,
  UserPlus,
  Equal,
  ChevronsUp,
  ChevronUp,
  ChevronsDown,
  MinusCircle,
  Briefcase,
  UserSquare,
  Network,
  MapPin,
  LayoutGrid,
  List,
  PieChart as PieChartIcon,
  BarChart3,
  MoreHorizontal,
  Figma,
  Bug,
  Flag,
  Bookmark,
  Shield,
  ShieldCheck,
  Star,
  ZapOff,
  UserCog,
  Wrench,
  ToggleLeft,
  Timer,
  Terminal,
  Tag,
  Trello,
  Trash,
  Ticket,
  Save,
  ThumbsUp,
  Table,
  Sword,
  Sun,
  Smartphone,
  Share,
  Send,
  SearchCode,
  Scissors,
  Rocket,
  Rewind,
  Repeat,
  RefreshCw,
  Recycle,
  Radio,
  Quote,
  Printer,
  Play,
  Plane,
  PieChart as PieIcon,
  Phone,
  Percent,
  PenTool,
  Pause,
  Package,
  Orbit,
  Option,
  Octagon,
  Navigation,
  Music,
  MousePointer,
  Mountain,
  Moon,
  Monitor,
  Mic,
  MessageCircle,
  Menu,
  Megaphone,
  Maximize,
  Map as MapIcon,
  Loader,
  Link as LinkIcon,
  LifeBuoy,
  Library,
  Laptop,
  Key,
  Info,
  Infinity,
  Inbox,
  Image,
  Home,
  Heart,
  Headphones,
  Hash,
  Hand,
  Hammer,
  Gift,
  Ghost,
  Gamepad,
  Fuel,
  Folder,
  FlaskConical,
  Flame,
  FileText,
  Eraser,
  Download,
  Dna,
  Disc,
  Diamond,
  Database as DBIcon,
  Crown,
  CreditCard,
  Cpu,
  Compass,
  Command,
  Cloud,
  Clipboard,
  Circle,
  Chrome,
  CheckSquare,
  Camera,
  Book,
  Bolt,
  Bluetooth,
  Bell,
  Battery,
  Award,
  AtSign,
  Archive,
  Anchor,
  Activity,
  Airplay,
  Coffee,
  Globe,
  AlarmClock,
  AlignCenter,
  Aperture,
  AppWindow,
  Apple,
  Armchair,
  Baby,
  Ban,
  BatteryCharging,
  BellOff,
  Braces,
  Calculator,
  Cast,
  ChevronsLeft,
  ChevronsRight,
  ClipboardCheck,
  ClipboardList,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  Code2,
  Coins,
  Cookie,
  Crosshair,
  Dribbble,
  Droplet,
  Dumbbell,
  Egg,
  EyeOff,
  Fan,
  FastForward,
  Feather,
  FileCode,
  FileJson,
  FileSearch,
  Fingerprint,
  Fish,
  FolderOpen,
  FolderPlus,
  Footprints,
  Frown,
  GanttChart,
  Gauge,
  Glasses,
  GraduationCap,
  HardDrive,
  Headset,
  IceCream,
  Languages,
  Lightbulb,
  Link2Off,
  Locate,
  LocateFixed,
  LogIn,
  MailOpen,
  Microscope,
  Milestone,
  Mouse,
  Music2,
  Nut,
  Palmtree,
  PartyPopper,
  PauseCircle,
  Pencil,
  PiggyBank,
  Plug,
  PlusCircle,
  Power,
  Puzzle,
  QrCode,
  Radar,
  Radiation,
  Rat,
  Receipt,
  RotateCcw,
  Route,
  Rss,
  Scale,
  Scan,
  School,
  ShieldAlert,
  ShieldQuestion,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrink,
  Shuffle,
  Sigma,
  Signal,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slack,
  Slash,
  Smile,
  Snowflake,
  Sofa,
  Speaker,
  Sprout,
  Square,
  Stamp,
  Stethoscope,
  Sticker,
  StickyNote,
  StopCircle,
  SunMoon,
  Sunrise,
  Sunset,
  Tablet,
  Tent,
  Thermometer,
  ThumbsDown,
  Tornado,
  ToyBrick,
  Train,
  TramFront,
  TreeDeciduous,
  TreePine,
  Trees,
  Truck,
  Tv,
  Tv2,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  Usb,
  UserCheck,
  UserMinus,
  Variable,
  Vibrate,
  Video,
  VideoOff,
  View,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand,
  Watch,
  Waves,
  Webcam,
  Webhook,
  Wheat,
  WholeWord,
  Wifi,
  Wind,
  Wine,
  Workflow,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Sparkles,
  Plus as PlusIcon,
  Grid,
  Box,
  HardHat,
  Construction,
  Settings2,
  BugPlay,
  FlaskRound,
  TestTube,
  Beaker,
  HeartPulse,
  Syringe,
  Pill,
  Atom,
  Binary,
  Flower2,
  Maximize2,
  Minimize2,
  DownloadCloud,
  FileCheck,
  FileWarning,
  HelpCircle,
  BarChart2,
  Presentation,
  MousePointer2,
  Keyboard,
  Server,
  TerminalSquare,
  Shell,
  Undo2,
  Redo2,
  Repeat2,
  Clock3,
  FileDigit,
  Contact,
  Building,
  Trophy,
  Medal,
  Gem,
  Bitcoin,
  Euro,
  PoundSterling,
  IndianRupee,
  JapaneseYen,
  UserX,
  Verified,
  Focus,
  ThermometerSnowflake,
  CloudHail,
  HandMetal,
  Dices,
  Brain,
  Pointer,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  FilePlus,
  MessageSquarePlus,
  UserPlus2,
  FileUp,
  Unlink,
  Lock as LockIcon,
  Link2 as Link2Icon,
  BellRing,
  RefreshCcw,
  PlusSquare,
  PackageOpen
} from 'lucide-react';

const AVAILABLE_ICONS = [
  { id: 'Zap', icon: Zap, label: 'Zap' },
  { id: 'CheckCircle2', icon: CheckCircle2, label: 'Check' },
  { id: 'CircleDot', icon: CircleDot, label: 'Dot' },
  { id: 'Bug', icon: Bug, label: 'Bug' },
  { id: 'ChevronsUp', icon: ChevronsUp, label: 'Highest' },
  { id: 'ChevronUp', icon: ChevronUp, label: 'High' },
  { id: 'Equal', icon: Equal, label: 'Medium' },
  { id: 'ChevronDown', icon: ChevronDown, label: 'Low' },
  { id: 'ChevronsDown', icon: ChevronsDown, label: 'Lowest' },
  { id: 'MinusCircle', icon: MinusCircle, label: 'Hold' },
  { id: 'Target', icon: Target, label: 'Target' },
  { id: 'Flag', icon: Flag, label: 'Flag' },
  { id: 'Bookmark', icon: Bookmark, label: 'Bookmark' },
  { id: 'AlertCircle', icon: AlertCircle, label: 'Alert' },
  { id: 'Clock', icon: Clock, label: 'Clock' },
  { id: 'Shield', icon: Shield, label: 'Shield' },
  { id: 'Star', icon: Star, label: 'Star' },
  { id: 'ZapOff', icon: ZapOff, label: 'Zap Off' },
  { id: 'Wrench', icon: Wrench, label: 'Wrench' },
  { id: 'Timer', icon: Timer, label: 'Timer' },
  { id: 'Terminal', icon: Terminal, label: 'Terminal' },
  { id: 'Tag', icon: Tag, label: 'Tag' },
  { id: 'Trello', icon: Trello, label: 'Trello' },
  { id: 'Ticket', icon: Ticket, label: 'Ticket' },
  { id: 'ThumbsUp', icon: ThumbsUp, label: 'Like' },
  { id: 'Sword', icon: Sword, label: 'Sword' },
  { id: 'Sun', icon: Sun, label: 'Sun' },
  { id: 'Smartphone', icon: Smartphone, label: 'Mobile' },
  { id: 'Rocket', icon: Rocket, label: 'Rocket' },
  { id: 'RefreshCw', icon: RefreshCw, label: 'Sync' },
  { id: 'PieIcon', icon: PieIcon, label: 'Chart' },
  { id: 'Package', icon: Package, label: 'Package' },
  { id: 'Orbit', icon: Orbit, label: 'Orbit' },
  { id: 'Moon', icon: Moon, label: 'Moon' },
  { id: 'Monitor', icon: Monitor, label: 'Desktop' },
  { id: 'Lock', icon: LockIcon, label: 'Lock' },
  { id: 'LifeBuoy', icon: LifeBuoy, label: 'Support' },
  { id: 'Layers', icon: Layers, label: 'Layers' },
  { id: 'Key', icon: Key, label: 'Key' },
  { id: 'Infinity', icon: Infinity, label: 'Infinity' },
  { id: 'Home', icon: Home, label: 'Home' },
  { id: 'Heart', icon: Heart, label: 'Heart' },
  { id: 'Globe', icon: Globe, label: 'Globe' },
  { id: 'Gift', icon: Gift, label: 'Gift' },
  { id: 'Gamepad', icon: Gamepad, label: 'Game' },
  { id: 'FileText', icon: FileText, label: 'File' },
  { id: 'Eye', icon: Eye, label: 'Eye' },
  { id: 'Diamond', icon: Diamond, label: 'Diamond' },
  { id: 'DBIcon', icon: DBIcon, label: 'Database' },
  { id: 'Crown', icon: Crown, label: 'Crown' },
  { id: 'Cpu', icon: Cpu, label: 'CPU' },
  { id: 'Coffee', icon: Coffee, label: 'Coffee' },
  { id: 'Cloud', icon: Cloud, label: 'Cloud' },
  { id: 'Bell', icon: Bell, label: 'Bell' },
  { id: 'Award', icon: Award, label: 'Award' },
  { id: 'Activity', icon: Activity, label: 'Activity' },
  { id: 'Anchor', icon: Anchor, label: 'Anchor' },
  { id: 'Archive', icon: Archive, label: 'Archive' },
  { id: 'AtSign', icon: AtSign, label: 'At' },
  { id: 'Battery', icon: Battery, label: 'Battery' },
  { id: 'Bluetooth', icon: Bluetooth, label: 'Bluetooth' },
  { id: 'Bolt', icon: Bolt, label: 'Bolt' },
  { id: 'Book', icon: Book, label: 'Book' },
  { id: 'Camera', icon: Camera, label: 'Camera' },
  { id: 'CheckSquare', icon: CheckSquare, label: 'Checkbox' },
  { id: 'Chrome', icon: Chrome, label: 'Chrome' },
  { id: 'Circle', icon: Circle, label: 'Circle' },
  { id: 'Clipboard', icon: Clipboard, label: 'Clipboard' },
  { id: 'Command', icon: Command, label: 'CMD' },
  { id: 'Compass', icon: Compass, label: 'Compass' },
  { id: 'CreditCard', icon: CreditCard, label: 'Card' },
  { id: 'Disc', icon: Disc, label: 'Disc' },
  { id: 'Dna', icon: Dna, label: 'DNA' },
  { id: 'Download', icon: Download, label: 'Download' },
  { id: 'Eraser', icon: Eraser, label: 'Eraser' },
  { id: 'ExtLink', icon: ExternalLink, label: 'Link' },
  { id: 'Flame', icon: Flame, label: 'Hot' },
  { id: 'FlaskConical', icon: FlaskConical, label: 'Lab' },
  { id: 'Folder', icon: Folder, label: 'Folder' },
  { id: 'Fuel', icon: Fuel, label: 'Fuel' },
  { id: 'Ghost', icon: Ghost, label: 'Ghost' },
  { id: 'Hammer', icon: Hammer, label: 'Hammer' },
  { id: 'Hand', icon: Hand, label: 'Hand' },
  { id: 'Hash', icon: Hash, label: 'Hash' },
  { id: 'Headphones', icon: Headphones, label: 'Audio' },
  { id: 'Image', icon: Image, label: 'Image' },
  { id: 'Inbox', icon: Inbox, label: 'Inbox' },
  { id: 'Info', icon: Info, label: 'Info' },
  { id: 'Laptop', icon: Laptop, label: 'Laptop' },
  { id: 'Library', icon: Library, label: 'Library' },
  { id: 'Map', icon: MapIcon, label: 'Map' },
  { id: 'Maximize', icon: Maximize, label: 'Expand' },
  { id: 'Megaphone', icon: Megaphone, label: 'News' },
  { id: 'Menu', icon: Menu, label: 'Menu' },
  { id: 'MessageCircle', icon: MessageCircle, label: 'Chat' },
  { id: 'Mic', icon: Mic, label: 'Mic' },
  { id: 'Mountain', icon: Mountain, label: 'Nature' },
  { id: 'Navigation', icon: Navigation, label: 'Nav' },
  { id: 'Octagon', icon: Octagon, label: 'Oct' },
  { id: 'Option', icon: Option, label: 'Opt' },
  { id: 'Pause', icon: Pause, label: 'Pause' },
  { id: 'PenTool', icon: PenTool, label: 'Draw' },
  { id: 'Percent', icon: Percent, label: 'Pct' },
  { id: 'Phone', icon: Phone, label: 'Phone' },
  { id: 'Plane', icon: Plane, label: 'Fly' },
  { id: 'Play', icon: Play, label: 'Play' },
  { id: 'Printer', icon: Printer, label: 'Print' },
  { id: 'Quote', icon: Quote, label: 'Quote' },
  { id: 'Radio', icon: Radio, label: 'Radio' },
  { id: 'Recycle', icon: Recycle, label: 'Recycle' },
  { id: 'Repeat', icon: Repeat, label: 'Repeat' },
  { id: 'Rewind', icon: Rewind, label: 'Rewind' },
  { id: 'Save', icon: Save, label: 'Save' },
  { id: 'Scissors', icon: Scissors, label: 'Cut' },
  { id: 'SearchCode', icon: SearchCode, label: 'Code' },
  { id: 'Send', icon: Send, label: 'Send' },
  { id: 'Share', icon: Share, label: 'Share' },
  { id: 'Table', icon: Table, label: 'Table' },
  { id: 'Trash', icon: Trash, label: 'Trash' },
  { id: 'AlarmClock', icon: AlarmClock, label: 'Alarm' },
  { id: 'AlignCenter', icon: AlignCenter, label: 'Align' },
  { id: 'Aperture', icon: Aperture, label: 'Lens' },
  { id: 'AppWindow', icon: AppWindow, label: 'App' },
  { id: 'Apple', icon: Apple, label: 'Apple' },
  { id: 'Armchair', icon: Armchair, label: 'Chair' },
  { id: 'Baby', icon: Baby, label: 'Baby' },
  { id: 'Ban', icon: Ban, label: 'Ban' },
  { id: 'BatteryCharging', icon: BatteryCharging, label: 'Charging' },
  { id: 'BellOff', icon: BellOff, label: 'Silent' },
  { id: 'Braces', icon: Braces, label: 'Code' },
  { id: 'Calculator', icon: Calculator, label: 'Calc' },
  { id: 'Cast', icon: Cast, label: 'Cast' },
  { id: 'ChevronsLeft', icon: ChevronsLeft, label: 'Back' },
  { id: 'ChevronsRight', icon: ChevronsRight, label: 'Next' },
  { id: 'ClipboardCheck', icon: ClipboardCheck, label: 'Check' },
  { id: 'ClipboardList', icon: ClipboardList, label: 'List' },
  { id: 'CloudDrizzle', icon: CloudDrizzle, label: 'Drizzle' },
  { id: 'CloudFog', icon: CloudFog, label: 'Fog' },
  { id: 'CloudLightning', icon: CloudLightning, label: 'Lightning' },
  { id: 'CloudMoon', icon: CloudMoon, label: 'Night' },
  { id: 'CloudRain', icon: CloudRain, label: 'Rain' },
  { id: 'CloudSnow', icon: CloudSnow, label: 'Snow' },
  { id: 'CloudSun', icon: CloudSun, label: 'Sunny' },
  { id: 'Code2', icon: Code2, label: 'Dev' },
  { id: 'Coins', icon: Coins, label: 'Coins' },
  { id: 'Cookie', icon: Cookie, label: 'Cookie' },
  { id: 'Crosshair', icon: Crosshair, label: 'Aim' },
  { id: 'Dribbble', icon: Dribbble, label: 'Dribble' },
  { id: 'Droplet', icon: Droplet, label: 'Drop' },
  { id: 'Dumbbell', icon: Dumbbell, label: 'Workout' },
  { id: 'Egg', icon: Egg, label: 'Egg' },
  { id: 'EyeOff', icon: EyeOff, label: 'Hide' },
  { id: 'Fan', icon: Fan, label: 'Fan' },
  { id: 'FastForward', icon: FastForward, label: 'Fast' },
  { id: 'Feather', icon: Feather, label: 'Feather' },
  { id: 'FileCode', icon: FileCode, label: 'Script' },
  { id: 'FileJson', icon: FileJson, label: 'JSON' },
  { id: 'FileSearch', icon: FileSearch, label: 'Find' },
  { id: 'Fingerprint', icon: Fingerprint, label: 'Bio' },
  { id: 'Fish', icon: Fish, label: 'Fish' },
  { id: 'FolderOpen', icon: FolderOpen, label: 'Open' },
  { id: 'FolderPlus', icon: FolderPlus, label: 'New' },
  { id: 'Footprints', icon: Footprints, label: 'Walk' },
  { id: 'Frown', icon: Frown, label: 'Sad' },
  { id: 'GanttChart', icon: GanttChart, label: 'Plan' },
  { id: 'Gauge', icon: Gauge, label: 'Speed' },
  { id: 'Glasses', icon: Glasses, label: 'Specs' },
  { id: 'GraduationCap', icon: GraduationCap, label: 'Grad' },
  { id: 'HardDrive', icon: HardDrive, label: 'Disk' },
  { id: 'Headset', icon: Headset, label: 'Audio' },
  { id: 'IceCream', icon: IceCream, label: 'Cold' },
  { id: 'Languages', icon: Languages, label: 'Lang' },
  { id: 'Lightbulb', icon: Lightbulb, label: 'Idea' },
  { id: 'Link2', icon: Link2Icon, label: 'Url' },
  { id: 'Link2Off', icon: Link2Off, label: 'NoLink' },
  { id: 'Locate', icon: Locate, label: 'Gps' },
  { id: 'LocateFixed', icon: LocateFixed, label: 'FixGps' },
  { id: 'LogIn', icon: LogIn, label: 'In' },
  { id: 'MailOpen', icon: MailOpen, label: 'Read' },
  { id: 'Microscope', icon: Microscope, label: 'Fine' },
  { id: 'Milestone', icon: Milestone, label: 'Mile' },
  { id: 'Mouse', icon: Mouse, label: 'Click' },
  { id: 'Music2', icon: Music2, label: 'Song' },
  { id: 'Nut', icon: Nut, label: 'Nut' },
  { id: 'Palmtree', icon: Palmtree, label: 'Beach' },
  { id: 'PartyPopper', icon: PartyPopper, label: 'Party' },
  { id: 'PauseCircle', icon: PauseCircle, label: 'Wait' },
  { id: 'Pencil', icon: Pencil, label: 'Write' },
  { id: 'PiggyBank', icon: PiggyBank, label: 'Bank' },
  { id: 'Plug', icon: Plug, label: 'Power' },
  { id: 'PlusCircle', icon: PlusCircle, label: 'Add' },
  { id: 'Power', icon: Power, label: 'On' },
  { id: 'Puzzle', icon: Puzzle, label: 'Game' },
  { id: 'QrCode', icon: QrCode, label: 'QR' },
  { id: 'Radar', icon: Radar, label: 'Radar' },
  { id: 'Radiation', icon: Radiation, label: 'Toxic' },
  { id: 'Rat', icon: Rat, label: 'Rat' },
  { id: 'Receipt', icon: Receipt, label: 'Bill' },
  { id: 'RotateCcw', icon: RotateCcw, label: 'Undo' },
  { id: 'Route', icon: Route, label: 'Route' },
  { id: 'Rss', icon: Rss, label: 'Rss' },
  { id: 'Scale', icon: Scale, label: 'Law' },
  { id: 'Scan', icon: Scan, label: 'Scan' },
  { id: 'School', icon: School, label: 'Edu' },
  { id: 'Search', icon: Search, label: 'Search' },
  { id: 'ShieldAlert', icon: ShieldAlert, label: 'Warn' },
  { id: 'ShieldCheck', icon: ShieldCheck, label: 'Safe' },
  { id: 'ShieldQuestion', icon: ShieldQuestion, label: 'Help' },
  { id: 'Shirt', icon: Shirt, label: 'Shirt' },
  { id: 'ShoppingBag', icon: ShoppingBag, label: 'Bag' },
  { id: 'ShoppingCart', icon: ShoppingCart, label: 'Cart' },
  { id: 'Shovel', icon: Shovel, label: 'Dig' },
  { id: 'ShowerHead', icon: ShowerHead, label: 'Bath' },
  { id: 'Shrink', icon: Shrink, label: 'Small' },
  { id: 'Shuffle', icon: Shuffle, label: 'Mix' },
  { id: 'Sigma', icon: Sigma, label: 'Sum' },
  { id: 'Signal', icon: Signal, label: 'Wifi' },
  { id: 'Siren', icon: Siren, label: 'Police' },
  { id: 'SkipBack', icon: SkipBack, label: 'Prev' },
  { id: 'SkipForward', icon: SkipForward, label: 'Skip' },
  { id: 'Skull', icon: Skull, label: 'Death' },
  { id: 'Slack', icon: Slack, label: 'Slack' },
  { id: 'Slash', icon: Slash, label: 'No' },
  { id: 'Smile', icon: Smile, label: 'Happy' },
  { id: 'Snowflake', icon: Snowflake, label: 'Cold' },
  { id: 'Sofa', icon: Sofa, label: 'Home' },
  { id: 'Speaker', icon: Speaker, label: 'Audio' },
  { id: 'Sprout', icon: Sprout, label: 'Grow' },
  { id: 'Square', icon: Square, label: 'Box' },
  { id: 'Stamp', icon: Stamp, label: 'Post' },
  { id: 'Stethoscope', icon: Stethoscope, label: 'Doc' },
  { id: 'Sticker', icon: Sticker, label: 'Sticky' },
  { id: 'StickyNote', icon: StickyNote, label: 'Note' },
  { id: 'StopCircle', icon: StopCircle, label: 'Stop' },
  { id: 'SunMoon', icon: SunMoon, label: 'DayNight' },
  { id: 'Sunrise', icon: Sunrise, label: 'Up' },
  { id: 'Sunset', icon: Sunset, label: 'Down' },
  { id: 'Tablet', icon: Tablet, label: 'Tab' },
  { id: 'Tent', icon: Tent, label: 'Camp' },
  { id: 'Thermometer', icon: Thermometer, label: 'Heat' },
  { id: 'ThumbsDown', icon: ThumbsDown, label: 'Dislike' },
  { id: 'Tornado', icon: Tornado, label: 'Wind' },
  { id: 'ToyBrick', icon: ToyBrick, label: 'Toy' },
  { id: 'Train', icon: Train, label: 'Travel' },
  { id: 'TramFront', icon: TramFront, label: 'City' },
  { id: 'TreeDeciduous', icon: TreeDeciduous, label: 'Park' },
  { id: 'TreePine', icon: TreePine, label: 'Forest' },
  { id: 'Trees', icon: Trees, label: 'Nature' },
  { id: 'Truck', icon: Truck, label: 'Ship' },
  { id: 'Tv', icon: Tv, label: 'TV' },
  { id: 'Tv2', icon: Tv2, label: 'TV2' },
  { id: 'Type', icon: Type, label: 'Font' },
  { id: 'Umbrella', icon: Umbrella, label: 'Safe' },
  { id: 'Underline', icon: Underline, label: 'Mark' },
  { id: 'Unlock', icon: Unlock, label: 'Open' },
  { id: 'Upload', icon: Upload, label: 'Up' },
  { id: 'UploadCloud', icon: UploadCloud, label: 'CloudUp' },
  { id: 'Usb', icon: Usb, label: 'Plug' },
  { id: 'UserCheck', icon: UserCheck, label: 'UserOk' },
  { id: 'UserCog', icon: UserCog, label: 'UserSet' },
  { id: 'UserMinus', icon: UserMinus, label: 'UserDel' },
  { id: 'Variable', icon: Variable, label: 'Var' },
  { id: 'Vibrate', icon: Vibrate, label: 'Vib' },
  { id: 'Video', icon: Video, label: 'Video' },
  { id: 'VideoOff', icon: VideoOff, label: 'NoVideo' },
  { id: 'View', icon: View, label: 'Look' },
  { id: 'Voicemail', icon: Voicemail, label: 'Voice' },
  { id: 'Volume', icon: Volume, label: 'Vol3' },
  { id: 'Volume1', icon: Volume1, label: 'Vol1' },
  { id: 'Volume2', icon: Volume2, label: 'Vol2' },
  { id: 'VolumeX', icon: VolumeX, label: 'Mute' },
  { id: 'Wallet', icon: Wallet, label: 'Cash' },
  { id: 'Wand', icon: Wand, label: 'Magic' },
  { id: 'Watch', icon: Watch, label: 'Time' },
  { id: 'Waves', icon: Waves, label: 'Ocean' },
  { id: 'Webcam', icon: Webcam, label: 'Cam' },
  { id: 'Webhook', icon: Webhook, label: 'Hook' },
  { id: 'Wheat', icon: Wheat, label: 'Farm' },
  { id: 'WholeWord', icon: WholeWord, label: 'Word' },
  { id: 'Wifi', icon: Wifi, label: 'Wifi' },
  { id: 'Wind', icon: Wind, label: 'Wind' },
  { id: 'Wine', icon: Wine, label: 'Drink' },
  { id: 'Workflow', icon: Workflow, label: 'Flow' },
  { id: 'XCircle', icon: XCircle, label: 'NoCircle' },
  { id: 'XOctagon', icon: XOctagon, label: 'NoOct' },
  { id: 'XSquare', icon: XSquare, label: 'NoSquare' },
  { id: 'Youtube', icon: Youtube, label: 'Video' },
  { id: 'Sparkles', icon: Sparkles, label: 'New' },
  { id: 'PlusIcon', icon: PlusIcon, label: 'Plus' },
  { id: 'Grid', icon: Grid, label: 'Grid' },
  { id: 'Box', icon: Box, label: 'Box' },
  { id: 'HardHat', icon: HardHat, label: 'Safe' },
  { id: 'Construction', icon: Construction, label: 'Site' },
  { id: 'Settings2', icon: Settings2, label: 'Config' },
  { id: 'BugPlay', icon: BugPlay, label: 'Debug' },
  { id: 'FlaskRound', icon: FlaskRound, label: 'Flask' },
  { id: 'TestTube', icon: TestTube, label: 'Test' },
  { id: 'Beaker', icon: Beaker, label: 'Beaker' },
  { id: 'HeartPulse', icon: HeartPulse, label: 'Pulse' },
  { id: 'Syringe', icon: Syringe, label: 'Syringe' },
  { id: 'Pill', icon: Pill, label: 'Pill' },
  { id: 'Atom', icon: Atom, label: 'Atom' },
  { id: 'Binary', icon: Binary, label: 'Binary' },
  { id: 'Flower2', icon: Flower2, label: 'Flower' },
  { id: 'Maximize2', icon: Maximize2, label: 'Full' },
  { id: 'Minimize2', icon: Minimize2, label: 'Min' },
  { id: 'DownloadCloud', icon: DownloadCloud, label: 'CloudDown' },
  { id: 'FileCheck', icon: FileCheck, label: 'FileOk' },
  { id: 'FileWarning', icon: FileWarning, label: 'FileErr' },
  { id: 'AlertTriangle', icon: AlertTriangle, label: 'Warn' },
  { id: 'HelpCircle', icon: HelpCircle, label: 'Help' },
  { id: 'BarChart2', icon: BarChart2, label: 'Stats' },
  { id: 'Presentation', icon: Presentation, label: 'Show' },
  { id: 'MousePointer2', icon: MousePointer2, label: 'Cursor' },
  { id: 'Keyboard', icon: Keyboard, label: 'Keybd' },
  { id: 'Server', icon: Server, label: 'Server' },
  { id: 'TerminalSquare', icon: TerminalSquare, label: 'Term' },
  { id: 'Shell', icon: Shell, label: 'Shell' },
  { id: 'Undo2', icon: Undo2, label: 'Undo' },
  { id: 'Redo2', icon: Redo2, label: 'Redo' },
  { id: 'Repeat2', icon: Repeat2, label: 'Cycle' },
  { id: 'Clock3', icon: Clock3, label: 'Clock3' },
  { id: 'FileDigit', icon: FileDigit, label: 'Data' },
  { id: 'Contact', icon: Contact, label: 'Contact' },
  { id: 'Building', icon: Building, label: 'Build' },
  { id: 'Trophy', icon: Trophy, label: 'Trophy' },
  { id: 'Medal', icon: Medal, label: 'Medal' },
  { id: 'Gem', icon: Gem, label: 'Gem' },
  { id: 'Bitcoin', icon: Bitcoin, label: 'Btc' },
  { id: 'Euro', icon: Euro, label: 'Euro' },
  { id: 'PoundSterling', icon: PoundSterling, label: 'Pound' },
  { id: 'IndianRupee', icon: IndianRupee, label: 'Rupee' },
  { id: 'JapaneseYen', icon: JapaneseYen, label: 'Yen' },
  { id: 'UserX', icon: UserX, label: 'UserX' },
  { id: 'Verified', icon: Verified, label: 'Verif' },
  { id: 'Focus', icon: Focus, label: 'Focus' },
  { id: 'Sunrise2', icon: Sunrise, label: 'SunUp' },
  { id: 'Sunset2', icon: Sunset, label: 'SunDown' },
  { id: 'ThermometerSnowflake', icon: ThermometerSnowflake, label: 'Temp' },
  { id: 'Tornado2', icon: Tornado, label: 'Wind2' },
  { id: 'CloudHail', icon: CloudHail, label: 'Hail' },
  { id: 'HandMetal', icon: HandMetal, label: 'Rock' },
  { id: 'Dices', icon: Dices, label: 'Luck' },
  { id: 'Brain', icon: Brain, label: 'Brain' },
  { id: 'Pointer', icon: Pointer, label: 'Pointer' },
  { id: 'ArrowLeft', icon: ArrowLeft, label: 'Left' },
  { id: 'ArrowUp', icon: ArrowUp, label: 'Up' },
  { id: 'ArrowDown', icon: ArrowDown, label: 'Down' },
  { id: 'FilePlus', icon: FilePlus, label: 'File+' },
  { id: 'MessageSquarePlus', icon: MessageSquarePlus, label: 'Msg+' },
  { id: 'UserPlus2', icon: UserPlus2, label: 'User+' },
  { id: 'ShieldCheck2', icon: ShieldCheck, label: 'ShieldOk' },
  { id: 'ShieldAlert2', icon: ShieldAlert, label: 'ShieldWarn' },
  { id: 'ShieldQuestion2', icon: ShieldQuestion, label: 'Shield?' },
];

const RenderIcon = ({ iconName, className, style }: { iconName?: string; className?: string; style?: any }) => {
  const iconObj = AVAILABLE_ICONS.find(i => i.id === iconName);
  const IconComponent = iconObj ? iconObj.icon : CircleDot;
  return <IconComponent className={className} style={style} />;
};

export { AVAILABLE_ICONS, RenderIcon };